In [2]:
import numpy as np
import pandas as pd
from count_processing.experiment import Experiment, SelfNonTargetingExperiment
from pathlib import Path

In [3]:
df = pd.read_csv("BarcodedCounts/unfiltered/2026-04-27_V00-TPT_ACTAGG_counts.csv", index_col=0)
df

,fmt_1_37_B_MM12,fmt_1_37_B_MM13,fmt_1_37_B_MM4,fmt_1_37_C,fmt_1_37_MM8,fmt_2_104_C,fmt_2_104_MM10,fmt_2_104_MM4,fmt_2_104_MM6,fmt_3_222_B_MM2,...,thyA_1_60_B_MM2,thyA_1_60_C,thyA_2_111_C,thyA_2_111_MM4,thyA_2_111_MM8,thyA_3_233_B_MM4,thyA_3_233_B_MM5,thyA_3_233_B_MM6,thyA_3_233_B_MM7,thyA_3_233_C
fmt_1_37_B_MM12,141.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
fmt_1_37_B_MM13,0.0,420.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
fmt_1_37_B_MM4,0.0,1.0,126.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
fmt_1_37_C,0.0,0.0,0.0,237.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
fmt_1_37_MM8,0.0,0.0,0.0,0.0,401.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
thyA_3_233_B_MM4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,524.0,0.0,0.0,0.0,0.0
thyA_3_233_B_MM5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,0.0,469.0,0.0,0.0,0.0
thyA_3_233_B_MM6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,380.0,0.0,0.0
thyA_3_233_B_MM7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,660.0,0.0
thyA_3_233_C,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,821.0

In [4]:
df["negC_rand_42"]["negC_rand_42"]

315247.0

In [5]:
experiment = SelfNonTargetingExperiment(
    counts_directory=Path("BarcodedCounts/unfiltered"),
    vial_id="V03",
    timepoints=["T-3", "T00", "T02", "T04", "T06", "T08", "T10"],
    barcodes=["TGAAAG", "CATGAT", "CCATGC", "TCATAC", "TAGACT", "ACTAGG", "Other"],
    sgRNAs=Path("PW_Folate_corrected.fa"),
    neg_control_sgRNA="negC_rand_42",
)

In [6]:
tp = experiment.read_time_library()

In [7]:
tp

                   fmt_1_37_B_MM12  fmt_1_37_B_MM13  fmt_1_37_B_MM4  \
timepoint barcode
T-3       ACTAGG            1431.0           1889.0          1344.0
          CATGAT            1212.0           1890.0           839.0
          CCATGC            1357.0           1315.0          1031.0
          Other              192.0            238.0           121.0
          TAGACT            2466.0           2697.0          1064.0
          TCATAC            1106.0           1038.0           998.0
          TGAAAG            1117.0           1910.0           746.0
T00       ACTAGG            1183.0           1399.0           659.0
          CATGAT             968.0           1582.0           511.0
          CCATGC            1065.0           1071.0           562.0
          Other              124.0            122.0            83.0
          TAGACT            1840.0           2253.0           587.0
          TCATAC             838.0            697.0           530.0
          TGAAAG             955.0           1705.0           416.0
T02       ACTAGG            1198.0           1165.0           125.0
          CATGAT             679.0           1285.0            90.0
          CCATGC            1456.0           1151.0            42.0
          Other              113.0            150.0            10.0
          TAGACT            1801.0           2031.0           128.0
          TCATAC             838.0            745.0            91.0
          TGAAAG             862.0           1633.0            47.0
T04       ACTAGG            1103.0           1195.0            44.0
          CATGAT             707.0           1104.0            32.0
          CCATGC             911.0            895.0            45.0
          Other               87.0            110.0             4.0
          TAGACT            1498.0           1670.0            64.0
          TCATAC             661.0            667.0            34.0
          TGAAAG             659.0           1175.0            13.0
T06       ACTAGG            2139.0           2044.0             9.0
          CATGAT            1252.0           1901.0            27.0
          CCATGC            1857.0           1889.0             3.0
          Other              217.0            225.0             2.0
          TAGACT            3037.0           3098.0            42.0
          TCATAC            1248.0            833.0            39.0
          TGAAAG            1173.0           2276.0             6.0
T08       ACTAGG            1645.0           1330.0            11.0
          CATGAT             858.0           1264.0            25.0
          CCATGC            1285.0           1390.0            31.0
          Other              143.0            163.0             1.0
          TAGACT            2056.0           2012.0            25.0
          TCATAC             852.0            623.0             8.0
          TGAAAG             885.0           1478.0             5.0
T10       ACTAGG            1632.0           1414.0             2.0
          CATGAT             771.0           1509.0            10.0
          CCATGC            1468.0           1345.0             4.0
          Other              144.0            174.0             0.0
          TAGACT            2191.0           2175.0            63.0
          TCATAC             880.0            684.0             5.0
          TGAAAG             982.0           1595.0             3.0

                   fmt_1_37_C  fmt_1_37_MM8  fmt_2_104_C  fmt_2_104_MM10  \
timepoint barcode
T-3       ACTAGG       1657.0        5668.0      26327.0         28807.0
          CATGAT       1333.0        6684.0      32084.0         34729.0
          CCATGC       1345.0        4368.0      23441.0         25350.0
          Other         154.0         678.0       2433.0          2841.0
          TAGACT       1010.0        5790.0      27204.0         31336.0
          TCATAC        757.0        3249.0      20502.0         21413.0
          TGAAAG       1369.0        5513.0      28026.0         27610.0
T00       ACTAGG        934.0        3743.0      20417.0         23515.0
          CATGAT        724.0        4171.0      26192.0         29801.0
          CCATGC        809.0        2766.0      17080.0         20486.0
          Other          75.0         480.0       2100.0          2338.0
          TAGACT        481.0        3866.0      20545.0         25138.0
          TCATAC        368.0        2231.0      15195.0         17157.0
          TGAAAG        727.0        3614.0      21846.0         22093.0
T02       ACTAGG        307.0        1532.0       9606.0         20944.0
          CATGAT        154.0        1301.0      10664.0         22858.0
          CCATGC        284.0         954.0       7463.0         17231.0
          Other          12.0         150.0        721.0          1596.0
          TAGACT        102.0        1593.0       9767.0         20549.0
          TCATAC         94.0         886.0       6423.0         13518.0
          TGAAAG        140.0        1411.0       9834.0         18368.0
T04       ACTAGG        103.0         613.0       4475.0         18031.0
          CATGAT         44.0         559.0       4901.0         19643.0
          CCATGC        132.0         390.0       3513.0         14544.0
          Other           9.0          53.0        345.0          1438.0
          TAGACT         55.0         634.0       5314.0         18273.0
          TCATAC         20.0         367.0       3205.0         11970.0
          TGAAAG         40.0         551.0       4446.0         15421.0
T06       ACTAGG        108.0         677.0       5073.0         34529.0
          CATGAT         59.0         387.0       5779.0         38256.0
          CCATGC        315.0         314.0       3041.0         24908.0
          Other          15.0          51.0        458.0          3008.0
          TAGACT         15.0         779.0       6617.0         32030.0
          TCATAC          8.0         279.0       3150.0         22145.0
          TGAAAG          7.0         533.0       4171.0         27849.0
T08       ACTAGG         49.0         327.0       2981.0         23529.0
          CATGAT          5.0         258.0       3005.0         26526.0
          CCATGC        121.0         202.0       1698.0         18768.0
          Other           9.0          35.0        221.0          1864.0
          TAGACT         16.0         403.0       4525.0         23388.0
          TCATAC          7.0         170.0       1732.0         15810.0
          TGAAAG         21.0         309.0       2749.0         19826.0
T10       ACTAGG         43.0         315.0       3354.0         24781.0
          CATGAT         15.0         252.0       3158.0         28616.0
          CCATGC         56.0         210.0       1768.0         18609.0
          Other           1.0          46.0        266.0          2306.0
          TAGACT          3.0         322.0       4592.0         23115.0
          TCATAC         10.0         218.0       1740.0         15829.0
          TGAAAG         15.0         318.0       2553.0         20764.0

                   fmt_2_104_MM4  fmt_2_104_MM6  fmt_3_222_B_MM2  ...  \
timepoint barcode                                                 ...
T-3       ACTAGG         25254.0        18095.0           1121.0  ...
          CATGAT         27922.0        21355.0           1986.0  ...
          CCATGC         19124.0        15938.0           2236.0  ...
          Other           2396.0         1621.0            137.0  ...
          TAGACT         25608.0        22366.0           1201.0  ...
          TCATAC         19620.0        13062.0            684.0  ...
          TGAAAG         22649.0        17655.0            849.0  ...
T00       ACTAGG         18954.0        14879.0            847.0  ...
          CATGAT         21954.0        17070.0           1789.0  ...
          CCATGC         13978.0        12232.0           1774.0  ...
          Other           1873.0         1438.0            122.0  ...
          TAGACT         19919.0        17714.0            736.0  ...
          TCATAC         14985.0        10380.0            519.0  ...
          TGAAAG         17593.0        13583.0            558.0  ...
T02       ACTAGG         13193.0         8546.0            172.0  ...
          CATGAT         13226.0         8834.0            500.0  ...
          CCATGC          7533.0         4968.0            443.0  ...
          Other            930.0          673.0             22.0  ...
          TAGACT         12601.0         9362.0            218.0  ...
          TCATAC         10601.0         4913.0             64.0  ...
          TGAAAG          9950.0         7239.0             93.0  ...
T04       ACTAGG          7711.0         4849.0             66.0  ...
          CATGAT          7501.0         4418.0            138.0  ...
          CCATGC          4758.0         3202.0            227.0  ...
          Other            552.0          349.0              7.0  ...
          TAGACT          7256.0         4885.0             72.0  ...
          TCATAC          5470.0         2773.0             57.0  ...
          TGAAAG          6033.0         3882.0             66.0  ...
T06       ACTAGG         10955.0         5840.0             40.0  ...
          CATGAT         11507.0         5817.0             57.0  ...
          CCATGC          5109.0         3388.0            218.0  ...
          Other            891.0          415.0             13.0  ...
          TAGACT          9434.0         6435.0             30.0  ...
          TCATAC          7821.0         2907.0             17.0  ...
          TGAAAG          7936.0         4924.0             10.0  ...
T08       ACTAGG          6397.0         3870.0             38.0  ...
          CATGAT          6226.0         3050.0             38.0  ...
          CCATGC          3192.0         2362.0            155.0  ...
          Other            465.0          239.0              5.0  ...
          TAGACT          5577.0         3833.0             11.0  ...
          TCATAC          4773.0         1755.0              5.0  ...
          TGAAAG          4531.0         2527.0             11.0  ...
T10       ACTAGG          5936.0         3883.0             10.0  ...
          CATGAT          5711.0         3160.0             34.0  ...
          CCATGC          2735.0         1977.0            120.0  ...
          Other            494.0          246.0              5.0  ...
          TAGACT          5480.0         3095.0             13.0  ...
          TCATAC          4441.0         1283.0             32.0  ...
          TGAAAG          4453.0         2380.0             31.0  ...

                   thyA_1_60_B_MM2  thyA_1_60_C  thyA_2_111_C  thyA_2_111_MM4  \
timepoint barcode
T-3       ACTAGG            2044.0        336.0       17995.0         14025.0
          CATGAT            2099.0        595.0       17713.0         15078.0
          CCATGC            1783.0        643.0       11805.0         11091.0
          Other              314.0         81.0        1735.0          1496.0
          TAGACT            1427.0        608.0       14571.0         13690.0
          TCATAC            1261.0        224.0        9788.0          9008.0
          TGAAAG            1519.0        438.0       13210.0          8892.0
T00       ACTAGG            1923.0        237.0       16513.0         13103.0
          CATGAT            2036.0        519.0       14276.0         14533.0
          CCATGC            1428.0        537.0       10398.0         10014.0
          Other              243.0         69.0        1542.0          1468.0
          TAGACT            1425.0        539.0       12213.0         12671.0
          TCATAC            1198.0        192.0        9088.0          8617.0
          TGAAAG            1571.0        371.0       11891.0          8220.0
T02       ACTAGG            1766.0         99.0        6735.0          6866.0
          CATGAT            1586.0        360.0        5311.0          7144.0
          CCATGC            1166.0        444.0        4444.0          4812.0
          Other              117.0         44.0         512.0           556.0
          TAGACT             894.0        478.0        4980.0          6292.0
          TCATAC            1093.0         93.0        3459.0          4310.0
          TGAAAG             783.0        306.0        4748.0          4086.0
T04       ACTAGG            1460.0        148.0        3116.0          3412.0
          CATGAT            1398.0        340.0        2492.0          3477.0
          CCATGC            1002.0        348.0        1958.0          2879.0
          Other              155.0         20.0         238.0           332.0
          TAGACT             828.0        286.0        2318.0          3217.0
          TCATAC             843.0        140.0        1730.0          2301.0
          TGAAAG             871.0        127.0        2118.0          2126.0
T06       ACTAGG            2626.0        240.0        1969.0          2563.0
          CATGAT            2607.0        938.0        1710.0          2989.0
          CCATGC            1730.0        582.0        1063.0          1811.0
          Other              286.0         89.0         203.0           282.0
          TAGACT            1302.0        604.0        1340.0          2560.0
          TCATAC            1638.0        152.0        1705.0          1833.0
          TGAAAG            1272.0        373.0        1406.0          1361.0
T08       ACTAGG            2167.0        161.0         928.0          1001.0
          CATGAT            1878.0        528.0         756.0          1237.0
          CCATGC            1064.0        521.0         665.0           813.0
          Other              189.0         59.0         100.0           119.0
          TAGACT             935.0        373.0         619.0          1225.0
          TCATAC            1356.0        106.0         772.0           853.0
          TGAAAG             885.0        247.0         640.0           649.0
T10       ACTAGG            2089.0        179.0        1062.0           978.0
          CATGAT            1804.0        596.0         772.0          1140.0
          CCATGC            1185.0        384.0         467.0          1005.0
          Other              228.0         68.0          77.0           102.0
          TAGACT             797.0        389.0         822.0          1211.0
          TCATAC            1960.0        103.0         895.0           863.0
          TGAAAG             899.0        219.0         870.0           547.0

                   thyA_2_111_MM8  thyA_3_233_B_MM4  thyA_3_233_B_MM5  \
timepoint barcode
T-3       ACTAGG          23640.0            2660.0            2275.0
          CATGAT          25317.0            1833.0            2891.0
          CCATGC          20925.0            2111.0            2163.0
          Other            2599.0             572.0             421.0
          TAGACT          23968.0            2451.0            3113.0
          TCATAC          17088.0            1567.0            1867.0
          TGAAAG          22316.0            2322.0            2029.0
T00       ACTAGG          23261.0            2393.0            2467.0
          CATGAT          25624.0            1628.0            3775.0
          CCATGC          21117.0            2329.0            2352.0
          Other            2872.0             492.0             456.0
          TAGACT          24166.0            2336.0            3318.0
          TCATAC          16632.0            1483.0            1993.0
          TGAAAG          22642.0            2357.0            2023.0
T02       ACTAGG          21089.0            2704.0            2421.0
          CATGAT          21182.0            1718.0            3660.0
          CCATGC          17597.0            2895.0            2360.0
          Other            1968.0             411.0             370.0
          TAGACT          22738.0            2303.0            3233.0
          TCATAC          14311.0            1607.0            1978.0
          TGAAAG          23164.0            2295.0            2377.0
T04       ACTAGG          21189.0            2469.0            2585.0
          CATGAT          19898.0            1850.0            3179.0
          CCATGC          16124.0            2336.0            2410.0
          Other            1989.0             347.0             367.0
          TAGACT          21622.0            2255.0            3115.0
          TCATAC          13827.0            1527.0            2045.0
          TGAAAG          19411.0            2265.0            2190.0
T06       ACTAGG          42536.0            5955.0            6039.0
          CATGAT          38721.0            3827.0            8261.0
          CCATGC          32919.0            5702.0            5109.0
          Other            4797.0             982.0            1054.0
          TAGACT          43537.0            4427.0            7149.0
          TCATAC          28935.0            3391.0            4434.0
          TGAAAG          48129.0            5459.0            4979.0
T08       ACTAGG          32057.0            4347.0            4745.0
          CATGAT          28640.0            2810.0            6365.0
          CCATGC          23712.0            4244.0            3856.0
          Other            3142.0             629.0             711.0
          TAGACT          32988.0            3045.0            5513.0
          TCATAC          21712.0            2410.0            3596.0
          TGAAAG          34258.0            3672.0            4183.0
T10       ACTAGG          34546.0            5042.0            5097.0
          CATGAT          30943.0            3569.0            7451.0
          CCATGC          24606.0            4519.0            4138.0
          Other            3819.0             850.0             890.0
          TAGACT          36079.0            3819.0            5910.0
          TCATAC          21936.0            2990.0            3690.0
          TGAAAG          38717.0            4439.0            4571.0

                   thyA_3_233_B_MM6  thyA_3_233_B_MM7  thyA_3_233_C
timepoint barcode
T-3       ACTAGG             3250.0            2459.0       11594.0
          CATGAT             3267.0            2706.0       11750.0
          CCATGC             3233.0            2261.0       10192.0
          Other               601.0             353.0        1930.0
          TAGACT             5171.0            2784.0       12793.0
          TCATAC             2734.0            1919.0        8292.0
          TGAAAG             3997.0            1304.0        9943.0
T00       ACTAGG             3236.0            2647.0       12128.0
          CATGAT             3522.0            2722.0       12239.0
          CCATGC             3131.0            2476.0       10381.0
          Other               655.0             381.0        2040.0
          TAGACT             5100.0            2970.0       13829.0
          TCATAC             2971.0            1672.0        8590.0
          TGAAAG             4274.0            1166.0       10461.0
T02       ACTAGG             3116.0            2311.0       13082.0
          CATGAT             3398.0            2937.0       11822.0
          CCATGC             3040.0            2406.0        9221.0
          Other               495.0             286.0        1554.0
          TAGACT             5704.0            3459.0       13012.0
          TCATAC             2867.0            1809.0        8268.0
          TGAAAG             5006.0            1160.0       10488.0
T04       ACTAGG             3385.0            2216.0       12586.0
          CATGAT             2892.0            2265.0       10506.0
          CCATGC             2719.0            2172.0        9466.0
          Other               455.0             272.0        1553.0
          TAGACT             4738.0            3005.0       12542.0

In [23]:
tp.xs("T-3", level="timepoint")["negC_rand_42"]

barcode
ACTAGG    595641.0
CATGAT    472330.0
CCATGC    482230.0
Other      56822.0
TAGACT    603535.0
TCATAC    389226.0
TGAAAG    360453.0
Name: negC_rand_42, dtype: float64